@baseUrl = http://localhost:3000
@jwtToken = {{authLogin.response.body.accessToken}}

# AUTH ########################################################################

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "123456"
}

# USER ########################################################################

### User Create
# @name userCreate
POST {{baseUrl}}/user
Content-Type: application/json

{
"name": "Víttor",
  "email": "user@gmail.com",
  "password": "123456"
}

### User Get
# @name userGet

GET {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

### User Patch
# @name userPatch

PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name": "Vitin"
}

### User Update Password
# @name userUpdatePassword

PATCH {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "password": "123456",
    "newPassword": "vitindograu"
}

### User Delete
# @name userDelete

DELETE {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

# POST ########################################################################

### Create post owned
# @name createPostOwned
POST {{baseUrl}}/post/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "title": "Título do pa",
  "excerpt": "Excerto do post",
  "content": "Conteúdo",
  "coverImageUrl": "http://localhost"
}

### Read one post public
# @name readOnePostPublic
GET {{baseUrl}}/post/titulo-do-pa-rw8b7b
Content-Type: application/json

### Read all post public
# @name readAllPostPublic
GET {{baseUrl}}/post
Content-Type: application/json

### Read one post owned
# @name readOnePostOwned
GET {{baseUrl}}/post/me/titulo-do-pa-mnkit6
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

### Read all post owned
# @name readAllPostOwned
GET {{baseUrl}}/post/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

