@baseUrl = http://localhost:3000
@jwtToken = {{authLogin.response.body.accessToken}}

# AUTH ########################################################################

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "vitindograu"
}

# USER ########################################################################

### User Create
# @name userCreate
POST {{baseUrl}}/user
Content-Type: application/json

{
"name": "Víttor",
  "email": "user@gmail.com",
  "password": "123456"
}

### User Get
# @name userGet

GET {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

### User Patch
# @name userPatch

PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name": "Vitin"
}

### User Update Password
# @name userUpdatePassword

PATCH {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "password": "123456",
    "newPassword": "vitindograu"
}

### User Delete
# @name userDelete

DELETE {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}